# permissions for end users to edit autounsealers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: autounsealer-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubberneddies-operator
    app.kubernetes.io/part-of: kubberneddies-operator
    app.kubernetes.io/managed-by: kustomize
  name: autounsealer-editor-role
rules:
- apiGroups:
  - api.tostieme.me
  resources:
  - autounsealers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.tostieme.me
  resources:
  - autounsealers/status
  verbs:
  - get
