---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.tostieme.me
  resources:
  - autounsealers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.tostieme.me
  resources:
  - autounsealers/finalizers
  verbs:
  - update
- apiGroups:
  - api.tostieme.me
  resources:
  - autounsealers/status
  verbs:
  - get
  - patch
  - update
